baseurl         = "https://www.dnahurnyi.com/about-me"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "dnahurnyi-com"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Denys Nahurnyi blog"
  subtitle    = "DENYS NAHURNYI"

  cover       = "img/space-cover-medium-min.jpg"
  description = "This is my blog"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "d_n826"
  linkedinName = "denys-nahurnyi"
  githubName = "dnahurnyi"

  logo = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/facebook/92/robot-face_1f916.png" # https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/320/google/40/robot-face_1f916.png
  orgName = "Nahurnyi Inc."
  orgWebsite = "https://www.dnahurnyi.com/about-me"
  orgDescription = "My startup company"

  author = "Denys Nahurnyi"
  authorAvatar = "img/author-min-min.jpg"
  authorLocation = "Lviv, UA"
  authorWebsite = "https://dnahurnyi.com/about-me"
  authorDescription = "Comedian"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Articles"
  url = "/tags/article/"
  weight = 100
